name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main    # Trigger on push to main branch

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: pypa Dependency Review
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
         inputs: requirements.txt 

      - name: Python security scan with Bandit
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          pip install bandit
          bandit -r QueueShield

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: .
          outputs: imageID
          tags: ${{ secrets.DOCKER_USERNAME }}/queueshield:latest

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/queueshield:latest
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push Docker image
        if: success()  # Push only if previous steps succeeded
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/queueshield:latest

      - name: Log out from Docker Hub
        run: docker logout
