name: Run Docker Container Daily

# Schedule the workflow to run at 00:00 UTC every day
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-docker-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/QueueShield:latest

      - name: Run Docker Container
        run: |
          docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
              -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
              ${{ secrets.DOCKER_USERNAME }}/queueshield:latest

      - name: Log out from Docker Hub
        run: docker logout
